spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/codebank}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER:codebank}
spring.datasource.password=${DB_PASSWORD:codebank}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
